import json
from pathlib import Path
p = Path(r'C:/Users/ThijsAntoniedeBoer/OneDrive - HELION/Dokumente/python-projects/price spread analysis copy.ipynb')
nb = json.loads(p.read_text(encoding='utf-8'))
new_cell = {
  "cell_type": "code",
  "execution_count": None,
  "metadata": {},
  "outputs": [],
  "source": [
"# --- Final comparison: daily revenue 2025 with and without headroom ---\n",
"price_file = list(Path('auction_spot_prices').glob('auction_spot_prices_switzerland_2025.csv'))[0]\n",
"csv = pd.read_csv(price_file, comment='#', dayfirst=True, parse_dates=['Delivery day'], keep_default_na=False)\n",
"if 'Hour 1' not in csv.columns:\n",
"    csv = pd.read_csv(price_file, comment='#', skiprows=1, dayfirst=True, parse_dates=['Delivery day'], keep_default_na=False)\n",
"hour_cols = [c for c in csv.columns if str(c).strip().startswith('Hour')]\n",
"hourly_long = csv.melt(id_vars=['Delivery day'], value_vars=hour_cols, var_name='hour', value_name='price').dropna(subset=['price']).copy()\n",
"hourly_long['hour'] = hourly_long['hour'].str.extract(r'Hour\\s*(\\d+)').astype(float)\n",
"hourly_long['timestamp'] = hourly_long['Delivery day'] + pd.to_timedelta(hourly_long['hour'] - 1, unit='h')\n",
"prices_2025 = hourly_long[['timestamp','price']].sort_values('timestamp').reset_index(drop=True)\n",
"prices_2025['price'] = pd.to_numeric(prices_2025['price'], errors='coerce')\n",
"prices_2025 = prices_2025.dropna(subset=['price']).reset_index(drop=True)\n",
"prices_2025 = prices_2025[prices_2025['timestamp'].dt.year == 2025].reset_index(drop=True)\n",
"if prices_2025.empty:\n",
"    raise ValueError('No 2025 prices loaded for final revenue comparison.')\n",
"# Build headroom from PV+EV if available\n",
"pv_ev = pd.read_excel(Path('PV+consumption_data/200pv_500ev.xlsx'))\n",
"col_strings = [str(c) for c in pv_ev.columns]\n",
"flow_col = None\n",
"for c in col_strings:\n",
"    lc = c.lower()\n",
"    if 'battery' in lc and 'power' in lc:\n",
"        flow_col = c\n",
"        break\n",
"if flow_col is None:\n",
"    for c in col_strings:\n",
"        lc = c.lower()\n",
"        if 'power' in lc:\n",
"            flow_col = c\n",
"            break\n",
"if flow_col is None:\n",
"    flow_col = pv_ev.select_dtypes(include='number').columns[0]\n",
"pv_ev['own_flow_kw'] = pd.to_numeric(pv_ev[flow_col], errors='coerce')\n",
"pv_ev['own_flow_mw'] = pv_ev['own_flow_kw'] / 1000.0\n",
"ts_col = None\n",
"for c in pv_ev.columns:\n",
"    lc = str(c).lower()\n",
"    if lc in ['timestamp','datetime','date']:\n",
"        ts_col = c\n",
"        break\n",
"if ts_col is None:\n",
"    dt_cols = [c for c in pv_ev.columns if pd.api.types.is_datetime64_any_dtype(pv_ev[c])]\n",
"    if dt_cols:\n",
"        ts_col = dt_cols[0]\n",
"if ts_col is None:\n",
"    raise ValueError('No timestamp-like column in PV/EV file')\n",
"pv_ev[ts_col] = pd.to_datetime(pv_ev[ts_col], errors='coerce')\n",
"pv_ev = pv_ev.dropna(subset=[ts_col,'own_flow_mw']).copy()\n",
"pv_ev['timestamp'] = pd.to_datetime(pv_ev[ts_col]).dt.floor('h')\n",
"pv_ev['arbitrage_headroom_mw'] = np.maximum(0, power - pv_ev['own_flow_mw'].abs())\n",
"prices_headroom = prices_2025.merge(pv_ev[['timestamp','arbitrage_headroom_mw']], on='timestamp', how='left')\n",
"prices_headroom['arbitrage_headroom_mw'] = prices_headroom['arbitrage_headroom_mw'].fillna(power)\n",
"prices_headroom['headroom_mw'] = np.minimum(power, prices_headroom['arbitrage_headroom_mw'])\n",
"def solve_hourly(prices_df, capacity, power, eta, max_daily_cycles, headroom=None):\n",
"    n = len(prices_df)\n",
"    eff_c = np.sqrt(eta)\n",
"    eff_d = np.sqrt(eta)\n",
"    soc = cp.Variable(n+1)\n",
"    charge = cp.Variable(n)\n",
"    discharge = cp.Variable(n)\n",
"    constr = [soc[0]==0, soc>=0, soc<=capacity, charge>=0, discharge>=0, charge<=power, discharge<=power]\n",
"    if headroom is not None:\n",
"        hr = np.minimum(power, headroom)\n",
"        hr_param = cp.Parameter(n, nonneg=True)\n",
"        hr_param.value = hr\n",
"        constr += [charge<=hr_param, discharge<=hr_param, charge+discharge<=hr_param]\n",
"    for t in range(n):\n",
"        constr.append(soc[t+1] == soc[t] + eff_c*charge[t] - discharge[t]/eff_d)\n",
"    for d, idxs in prices_df.groupby(prices_df['timestamp'].dt.floor('D')).groups.items():\n",
"        constr.append(cp.sum(discharge[list(idxs)]) <= max_daily_cycles * capacity)\n",
"    price_vec = prices_df['price'].to_numpy(dtype=float)\n",
"    prob = cp.Problem(cp.Maximize(price_vec @ (discharge - charge)), constr)\n",
"    prob.solve(solver=cp.SCS, verbose=False, max_iters=200000)\n",
"    if prob.status not in ['optimal','optimal_inaccurate']:\n",
"        raise RuntimeError('Solver failed')\n",
"    out = prices_df.copy()\n",
"    out['charge_mw'] = charge.value\n",
"    out['discharge_mw'] = discharge.value\n",
"    out['soc_mwh'] = soc.value[1:]\n",
"    out['revenue_eur'] = out['price'] * (out['discharge_mw'] - out['charge_mw'])\n",
"    daily = out.groupby(out['timestamp'].dt.floor('D'))['revenue_eur'].sum().reset_index(name='daily_revenue_eur')\n",
"    return out, daily, float(prob.value)\n",
"_, daily_no_headroom, rev_no = solve_hourly(prices_2025, capacity, power, round_trip_efficiency, max_daily_cycles, headroom=None)\n",
"_, daily_with_headroom, rev_headroom = solve_hourly(prices_headroom, capacity, power, round_trip_efficiency, max_daily_cycles, headroom=prices_headroom['headroom_mw'].to_numpy(dtype=float))\n",
"daily_plot = pd.merge(daily_no_headroom.rename(columns={'daily_revenue_eur':'daily_revenue_no_headroom'}), daily_with_headroom.rename(columns={'daily_revenue_eur':'daily_revenue_headroom'}), on='timestamp', how='outer').sort_values('timestamp').fillna(0)\n",
"print(f'Revenue no headroom: {rev_no:,.2f} EUR, with headroom: {rev_headroom:,.2f} EUR')\n",
"plt.figure(figsize=(14, 6))\n",
"plt.plot(daily_plot['timestamp'], daily_plot['daily_revenue_no_headroom'], label='2025 daily revenue (no headroom)', color='tab:blue', alpha=0.8)\n",
"plt.plot(daily_plot['timestamp'], daily_plot['daily_revenue_headroom'], label='2025 daily revenue (with headroom)', color='tab:orange', alpha=0.8)\n",
"plt.title('Daily 2025 arbitrage revenue: no headroom vs headroom')\n",
"plt.xlabel('Date')\n",
"plt.ylabel('Daily revenue (EUR)')\n",
"plt.legend()\n",
"plt.grid(True, alpha=0.3)\n",
"plt.tight_layout()\n",
"plt.show()\n"
  ]
}
nb['cells'].append(new_cell)
p.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('Appended final daily revenue comparison cell.')
